# Generated by Django 5.1.6 on 2025-02-12 05:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0003_relationship'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.CharField(max_length=280),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.CharField(default='Hola, Twitter', max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='relationship',
            unique_together={('from_user', 'to_user')},
        ),
    ]
